// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApplicationCore.Models
{
    public partial class Character
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime? BirthDay { get; set; }
        public string ImageUrl { get; set; }
        public string Description { get; set; }
        public string Career { get; set; }
    }
}